server:
  port: ${PORT:8081}

spring:
  cloud:
    gcp:
      sql:
        instance-connection-name: ${DB_INSTANCE_CONNECTION_NAME}
        database-name: sbps_device
  datasource:
    url: jdbc:postgresql:///${spring.cloud.gcp.sql.database-name}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

api:
  base-url: ${API_BASE_URL:http://localhost:8080}

service-user:
  email: ${SERVICE_USER_EMAIL:service-user@example.com}
  password: ${SERVICE_USER_PASSWORD:strongpassword}

mqtt:
  host: ${MQTT_HOST:broker.emqx.io}
  port: ${MQTT_PORT:1883}
  username: ${MQTT_USERNAME:guest}
  password: ${MQTT_PASSWORD:guest}

logging:
  level:
    root: WARN
    com.yh.sbps: INFO